apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-08-23T11:55:42Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: product
  name: product
  namespace: c7-t7-dev
  resourceVersion: "1423383"
  uid: fd1feb36-776f-4264-9ab1-cf34c23ad0df
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.172.98
  clusterIPs:
  - 10.0.172.98
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31913
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: product
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 52.226.101.71
