apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2022-08-23T11:46:48Z"
  generation: 3
  labels:
    app: product
  name: product
  namespace: c7-t7-dev
  resourceVersion: "1423213"
  uid: 7933812b-ae23-4867-961d-e5ceaf153c22
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: product
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product
    spec:
      containers:
      - image: mukesh1993/testaks:1
        imagePullPolicy: IfNotPresent
name: product
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-23T12:13:28Z"
    lastUpdateTime: "2022-08-23T12:13:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-23T12:03:43Z"
    lastUpdateTime: "2022-08-23T12:26:49Z"
    message: ReplicaSet "product-75b4cbb4ff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1